export const ha = {
  label: 'Hausa', lang: 'ha', link: '/ha/',
  description: 'DAT (Distributed Access Token) — ƙa\'idar token shiga da aka rarraba wadda ke ayyana karewa, yankin da aka ɓoye da sauya maɓalli ta takardar shaida a matsayin yarjejeniyar waya.',
  menu_docs: 'Takardu', menu_intro: 'Gabatarwa', menu_intro_index: 'Menene DAT?', menu_intro_ai: 'Vibe coding da AI',
  menu_spec: 'Ƙa\'ida', menu_spec_dat: 'DAT', menu_spec_cert: 'Takardun shaida', menu_spec_cms: 'DAT CMS', menu_spec_errors: 'Lambobin kuskure',
  err_impact_critical: 'Mai tsanani', err_impact_partial: 'Wani sashe', err_impact_none: 'Babu tasiri', err_retry_transient: 'Na wucin gadi', err_retry_permanent: 'Na dindindin', err_retry_state: 'Yanayi', err_suspect: 'Abin zargi', error_handling: 'Sarrafa kuskure',
  menu_libs: 'Dakunan karatu', menu_libs_index: 'Duk dakunan karatu', libs_intro: 'Abokan ciniki na hukuma na harsuna da yawa, dukkansu bisa binary protocol iri ɗaya. Zaɓi harshe don ganin umarnin shigarwa, misalai na asali da saitin takardun shaida.',
  menu_svc: 'Ayyuka', menu_svc_cms: 'DAT CMS', menu_tool: 'Kayan aiki', menu_tool_bytes: 'Mai canza byte', menu_tool_time: 'Mai canza lokacin Unix', menu_projects: 'Shirye-shirye',
  external_link: 'Yana buɗewa a sabon shafin', nav_prev: 'Shafin baya', nav_next: 'Shafi na gaba', platform_support: 'Dandamalin da ake goyon baya', download: 'Sauke', example: 'Misali', manual_code: 'Aiwatarwa da hannu', repository: 'Ma\'ajiya', structure: 'Tsari',
  page_not_found: 'Ba a sami shafin ba', copy_code: 'Kwafi lambar shiri', clear: 'Share', dat_cms: 'Aikin sarrafa takardun shaidar DAT', deploy_cmd: 'Umarnin gudanarwa', api_check: 'Duba API', server: 'Sabar', production: 'Yanayin samarwa', debug: 'Gyaran kuskure', db: 'Ma\'ajiyar bayanai',
  dat_expire: 'Lokacin karewa', dat_plain: 'Bayanan fili', dat_secure: 'Bayanan da aka ɓoye', gen: 'Ƙirƙira', gen_count: 'Adadin ƙirƙira', cert: 'Takardar shaidar DAT', cert_cron: 'Jadawalin ƙirƙirar takardun DAT (Cron)', cert_exp: 'Karewar takardar shaida', cert_issue_delay: 'Jinkirin bayar da takarda', dat_issue_start: 'Fara bayar da DAT', dat_issue_dur: 'Lokacin bayar da DAT', dat_ttl: 'DAT TTL (lokacin rayuwa)',
  gen_certs: 'Ƙirƙiri takardun DAT', sig: 'Sa hannu', alg: 'Hanyar lissafi', sig_alg: 'Hanyar lissafin sa hannu', sig_key: 'Maɓallin sa hannu', crypto: 'Ɓoyewa', crypto_alg: 'Hanyar lissafin ɓoyewa', crypto_key: 'Maɓallin ɓoyewa', export_key_pair: 'Fitar da maɓallan biyu (na sirri, na jama\'a)', export_verify_only: 'Fitar da maɓallin tabbatarwa (na jama\'a)',
  import_certs: 'Shigo da takardun DAT', mgr_certs: 'Sarrafa takardun DAT', issue_dat: 'Bayar da DAT', parse_dat: 'Nazartar DAT', paste_cert: 'Manna takardun DAT', paste_dat: 'Manna DAT', expired: 'Ya ƙare', issue_over: 'Bayarwa ta ƙare', not_issue_yet: 'Ba a iya amfani da shi don bayarwa ba tukuna', verify_only: 'Tabbatarwa kaɗai',
  access_control: 'Ikon shiga', master_token: 'Babban token', master_token_desc: 'Yana ƙirƙirar takardun DAT kuma yana karɓar sigar sabar', full_cert_token: 'Token na cikakkiyar takarda', full_cert_token_desc: 'Yana karɓar cikakkun takardu (key pair, hash key)', verify_cert_token: 'Token na takardar tabbatarwa', verify_cert_token_desc: 'Yana karɓar takardun tabbatarwa kaɗai (maɓallin tabbatarwa kawai)',
  tool_bytes_title: 'Mai canza Byte, Base64 da Hex', show_more_byte_tools: 'Nuna ƙarin kayan aikin byte', text: 'Rubutu', hash: 'Hash', upper: 'Babban harafi', bytes: 'Byte', input_text: 'Shigar da rubutu', input_base64: 'Shigar da Base64', input_hex: 'Shigar da Hex', seconds: 'daƙiƙu', default: 'Na asali', none: 'Babu', see: 'Duba', error: 'Kuskure', ignored: 'An yi watsi', log_file: 'Fayil na log',
  username: 'Sunan mai amfani', password: 'Kalmar sirri', host: 'Mai masauki', port: 'Tashar sadarwa', plain_text: 'Rubutun fili', secure_text: 'Rubutun da aka ɓoye', plain_hex: 'Hex na fili', secure_hex: 'Hex da aka ɓoye', kube_namespace: 'Yankin suna na Kubernetes', sqlite_path: 'Hanyar SQLite', api_cache: 'Ma\'ajiyar wucin gadi ta API', alnum_only: 'Yi amfani da haruffa da lambobi kawai',
  msg_parse_ok: 'Nazari ya yi nasara', msg_plain_empty: 'Bayanan fili babu komai', msg_secure_empty: 'Bayanan da aka ɓoye babu komai', msg_mariadb: 'Ana goyon bayan MariaDB ta ƙa\'idar MySQL.', err_unknown: 'Kuskuren da ba a sani ba', err_invalid_utf8: 'Rubutun UTF-8 ba daidai ba', err_odd_hex: 'Hex mai tsawon marar lamba biyu: an yi watsi da harafin ƙarshe.', err_invalid_base64: 'Base64 ba daidai ba',
  err_cert_empty: 'Jerin takardun shaida babu komai: manna ko ƙirƙiri takardu', err_select_cert: 'Da farko ƙirƙiri kuma zaɓi takarda', err_cert_exists: 'Takardar ta riga ta wanzu', err_cert_not_exist: 'Takardar ba ta wanzu', err_cert_not_issuable: 'Takardar ba za ta iya bayar da token ba', err_cert_expired: 'Takardar ta ƙare', err_invalid_token: 'Token ba daidai ba', err_invalid_issue_times: 'Lokutan bayarwa ba daidai ba (farawa, tsawo, TTL)',
  err_issue_begin_range: 'Fara bayarwa dole ya kasance tsakanin 0 da 253405000799999', err_issue_dur_range: 'Lokacin bayarwa dole ya fi daƙiƙu 0', err_dat_ttl_range: 'DAT TTL dole ya fi 0', err_gen_count_range: 'Adadin ƙirƙira dole ya kasance tsakanin 1 da 100', err_invalid_port: 'Lambar tashar sadarwa ba daidai ba', err_invalid_db_port: 'Lambar tashar sadarwar ma\'ajiyar bayanai ba daidai ba', err_invalid_db_cache: 'Lokacin ma\'ajiyar wucin gadi ta bayanai ba daidai ba (0–3600)',
  err_invalid_cron: 'Furucin Cron ba daidai ba', err_invalid_delay: 'Jinkirin bayarwa ba daidai ba', err_invalid_issue_dur: 'Lokacin bayar da DAT ba daidai ba', err_invalid_dat_ttl: 'DAT TTL ba daidai ba', err_invalid_kube_ns: 'Yankin suna na Kubernetes ba daidai ba', err_invalid_kube_replicas: 'Adadin kwafin Kubernetes ba daidai ba (1–12)',
  cms_certs: 'Takardun shaida', cms_status: 'Yanayi', cms_debug_mode_only: 'Yanayin gyaran kuskure kawai', cms_binary: 'Fayil ɗin aiwatarwa', cms_opt_env: 'Zaɓuɓɓuka (masu canjin muhalli)', cms_opt_hostname_desc: 'Ana amfani da shi a sunayen fayil ɗin rajista kawai', cms_opt_port_desc: 'Tashar sadarwar aiki', cms_opt_db_uri_desc: 'URI na ma\'ajiyar bayanai', cms_supported: 'Ana goyon baya', cms_opt_debug_desc: 'Yanayin gyaran kuskure', cms_opt_log_console_desc: 'Fitarwar konsol', cms_no_out: 'Babu fitarwa',
  cms_value: 'Ƙima', cms_log_text_desc: 'Yi amfani da fayil ɗin rajistar rubutu', cms_log_json_desc: 'Yi amfani da fayil ɗin rajistar JSON (don ELK)', cms_no_log_file: 'Babu fayil ɗin rajista', cms_disabled: 'An kashe', cms_schedule: 'Jadawali', cms_set_default_value: 'Saita ƙimar asali', cms_k8s_multi_pods_example: 'Misalin Kubernetes mai pods da yawa', cms_ex: 'Misali:',
  cms_help_cert_issue_delay: `
        Bayan ƙirƙirar takardar shaida, ana jinkirta bayarwa har jinkirin da aka saita ya wuce.<br/>
        Wannan lokaci yana bai wa sabobi daban a cluster damar daidaita sabuwar takarda.<br/>
        Misali, DAT CMS ya ƙirƙiri takarda A, sabar 1 da 2 suna karɓarta kowane daƙiƙu 60.<br/>
        Idan sabar 1 ta karɓe ta farko ta bayar da DAT kafin sabar 2 ta daidaita, sabar 2 ba za ta iya tabbatarwa ko parse DAT ɗin ba.<br/>
        Idan an saita daƙiƙu 180, takardar ba za ta iya bayar da token a daƙiƙu 180 na farko bayan ƙirƙira ba.<br/>
        Bayarwa tana farawa bayan wannan lokaci, tana bai wa sauran sabobi lokacin daidaitawa lafiya.<br/>
        Don la'akari da kuskuren cibiyar sadarwa na wucin gadi, saita ƙima aƙalla sau uku ko huɗu na tazarar lokacin daidaitawar sabobi.`,
  cms_help_dat_issue_dur: `
        Lokacin da takardar za ta iya bayar da DAT bayan <b>{cert_issue_delay}</b> ya ƙare.<br/>
        Bayan wannan lokaci takardar ba za ta iya bayar da sabon DAT ba; za ta iya tabbatarwa da nazartar waɗanda aka riga aka bayar kawai.`,
  cms_help_dat_ttl: `
        Tsawon lokacin da DAT da aka bayar yake da inganci.<br/>
        Ko bayan <b>{cert_issue_delay}</b> ya ƙare, takardar tana nan don nazari da tabbatarwa na <b>{dat_ttl}</b> domin DAT da aka bayar su riƙe cikakken rayuwarsu.<br/>
        Takardar tana ƙare gaba ɗaya bayan jimillar lokacin <b>{cert_issue_delay}</b> + <b>{dat_ttl}</b> ta wuce.`,
  cms_help_cert_cron: `
        Furucin Cron don ƙirƙirar sabbin takardun shaida lokaci-lokaci.<br/>
        Yi la'akari da <b>{cert_issue_delay}</b> da <b>{dat_issue_dur}</b> don kada tazarar lokaci ta yi tsawo sosai.<br/>
        Gajeriyar tazarar lokaci tana ƙirƙirar takardu da yawa kuma tana ɓata albarkatun sabobin da ke daidaita su; zaɓi yawan da ya dace da aiki.`,
  bench_title: 'Aiki', bench_note: 'An auna a Mac mini M4 na asali na 2024 (cibiya 10) · Zane-zane suna nuna IV-AES256-GCM kawai', bench_table: 'Bayanan asali (ms ga ayyuka 10,000)', bench_issue: 'Bayar da DAT 10,000', bench_parse: 'Nazartar DAT 10,000', bench_multi: 'Zaren aiki da yawa', bench_single: 'Zaren aiki guda',
}
