import type { SharedGuideLocale } from './types'

export const bnGuideLocale: SharedGuideLocale = {
 libraryIndex:{title:'লাইব্রেরি',intro:'আপনার application-এর ভাষার DAT client বাছুন। প্রতিটি client একই DAT ও certificate specification ব্যবহার করে এবং local certificate management ও DAT CMS synchronization দেয়।',criteriaTitle:'যেভাবে বাছবেন',criteriaBody:'DAT ইস্যুকারী service-কে full certificates ব্যবহার করতে হবে। শুধু verify ও decrypt করা service-এর ECDSA verify-only certificates এবং CMS verify-only role ব্যবহার করা উচিত।',flowTitle:'Guide-এর গঠন',flowBody:'প্রতিটি library guide-এ installation, সহজ issuance ও verification flow, DAT CMS connection, synchronization policy, shutdown ও error handling আছে।'},
 library:{titleSuffix:'লাইব্রেরি',install:'Installation',quickTitle:'দ্রুত শুরু',quickIntro:'এই সম্পূর্ণ flow CMS থেকে certificates আনে, JSON data-সহ DAT তৈরি করে এবং যাচাই করে।',stepTitle:'ধাপে ধাপে',connectTitle:'1. CMS-এ সংযোগ',connectBody:'Issuing service full certificates-এর token ব্যবহার করে। startup-এ সঙ্গে সঙ্গে synchronize করলে certificates পাওয়ার আগে issuance হয় না।',issueTitle:'2. DAT ইস্যু',issueBody:'এই উদাহরণে public JSON `plain`-এ এবং protected user information JSON হিসেবে `secure`-এ রাখা হয়।',parseTitle:'3. DAT যাচাই',parseBody:'`parse` expiration ও signature যাচাই করে, তারপর `secure` decrypt করে। সফল verification-এর পরের payload-ই ব্যবহার করুন।',functionsTitle:'মূল functions',functionHeader:'Function',purposeHeader:'উদ্দেশ্য',dataTitle:'Data regions',plainBody:'signed কিন্তু encrypted নয় এমন bytes।',secureBody:'encrypted bytes।',payloadBody:'`parse` সফল হলেই বিশ্বাস করুন।',optionsTitle:'JSON ছাড়াও বিকল্প',optionsBody:'উদাহরণে পরিচিত JSON ব্যবহৃত। দ্রুত processing-এর জন্য binary data JSON serialization ও parsing এড়িয়ে data size কমাতে পারে।',formatsBody:'Simple values text হিসেবে বা structured data Protobuf/MessagePack-এর মতো binary format-এ `plain` ও `secure`-এ রাখুন।',verifyTitle:'Verify-only services',verifyBody:'DAT issue না করা service verify-only option ও verify-only token ব্যবহার করে এবং শুধু `parse` call করে।',lifecycleTitle:'Shutdown ও errors',errorsBefore:'Error messages-এর বদলে ',errorsLink:'error codes ও retry classifications',errorsAfter:' ব্যবহার করুন।'},
 guides:{
  rust:{binaryNote:'`issue` বর্তমানে strings নেয়, তাই arbitrary bytes Base64Url বা Hex-এ encode করে verification-এর পর decode করুন।',lifecycle:'শেষ `Arc<DatCmsManager>` drop হলে automatic synchronization task শেষ হয়।',apiPurposes:['Certificates সঙ্গে সঙ্গে synchronize করে।','বর্তমান issuing certificate দিয়ে DAT তৈরি করে।','DAT verify করে payload ফেরায়।','শেষ synchronization error ফেরায়।']},
  java:{binaryNote:'`ByteArray` overload অতিরিক্ত format ছাড়াই bytes সরাসরি রাখে ও আনে।',lifecycle:'`DatCmsManager` হলো `AutoCloseable`; `use` বা `close()` দিয়ে বন্ধ করুন।',apiPurposes:['Certificates সঙ্গে সঙ্গে synchronize করে এবং failure জানায়।','DAT তৈরি করে DatResult ফেরায়।','DAT verify করে Payload ফেরায়।','শেষ background synchronization error ফেরায়।']},
  javascript:{binaryNote:'`Uint8Array` বা `ArrayBuffer` দিন এবং `plainBytes` ও `secureBytes` দিয়ে মূল bytes নিন।',lifecycle:'shutdown-এ timers ও চলমান requests পরিষ্কার করতে `stop()` call করুন।',apiPurposes:['Certificates সঙ্গে সঙ্গে synchronize করে।','Asynchronously DAT string তৈরি করে।','DAT verify করে DatPayload ফেরায়।','শেষ synchronization error ফেরায়।']},
  python:{binaryNote:'সরাসরি `bytes` দিন এবং `plain_bytes` ও `secure_bytes` দিয়ে নিন।',lifecycle:'automatic synchronization চালু থাকলে shutdown-এ `stop()` call করুন।',apiPurposes:['Certificates সঙ্গে সঙ্গে synchronize করে।','DAT string তৈরি করে।','DAT verify করে DatPayload ফেরায়।','শেষ synchronization error ফেরায়।']},
  csharp:{binaryNote:'`byte[]` overload এবং `PlainBytes` ও `SecureBytes` ব্যবহার করুন।',lifecycle:'manager ও background synchronization পরিষ্কারে `await using` ব্যবহার করুন।',apiPurposes:['Certificates সঙ্গে সঙ্গে synchronize করে।','DAT string তৈরি করে।','DAT verify করে Payload ফেরায়।','শেষ synchronization error ফেরায়।']},
  go:{binaryNote:'Go strings bytes রাখতে পারে। byte slice `string` হিসেবে দিয়ে result আবার `[]byte`-এ বদলান।',lifecycle:'automatic synchronization চালু থাকলে cleanup নিশ্চিত করতে `defer cms.Close()` ব্যবহার করুন।',apiPurposes:['Certificates সঙ্গে সঙ্গে synchronize করে।','DAT string ও error ফেরায়।','Verified Payload ও error ফেরায়।','শেষ synchronization error ফেরায়।']},
  ruby:{binaryNote:'Binary strings দিন এবং `plain_bytes` ও `secure_bytes` দিয়ে নিন।',lifecycle:'automatic synchronization চালু থাকলে background thread শেষ করতে `stop` call করুন।',apiPurposes:['Certificates সঙ্গে সঙ্গে synchronize করে।','DAT string তৈরি করে।','DAT verify করে DatPayload ফেরায়।','শেষ synchronization error ফেরায়।']},
  c:{binaryNote:'বর্তমান C issuance API NUL-terminated strings নেয়। arbitrary bytes Base64Url বা Hex-এ encode করে payload lengths দিয়ে result পড়ুন।',lifecycle:'নিজ নিজ cleanup function দিয়ে `dat`, `payload` ও `cms` release করুন।',apiPurposes:['Certificates সঙ্গে সঙ্গে synchronize করে।','DAT string allocate করে ফেরায়।','Verified payload allocate করে ফেরায়।','শেষ synchronization error ফেরায়।'],parse:`dat_payload_t *payload = NULL;
err = dat_cms_manager_parse(cms, dat, &payload);
/* plain_bytes ও secure_bytes তাদের নিজস্ব length-সহ ব্যবহার করুন। */`,binary:`/* issue C strings নেয়, তাই NUL-যুক্ত data আগে encode করুন। */
const char *secure_hex = "00ff1080";
char *dat = NULL;
err = dat_cms_manager_issue(cms, "01", secure_hex, &dat);

dat_payload_t *payload = NULL;
err = dat_cms_manager_parse(cms, dat, &payload);`}},
 cms:{introBefore:'DAT CMS certificates তৈরি করে, database-এ রাখে এবং issuing ও verifying services-এ উপযুক্ত certificates দেয়। Protocol behavior ',specLink:'DAT CMS specification',introAfter:'-এ বর্ণিত।',configTitle:'Runtime configuration তৈরি',dockerTitle:'Docker দিয়ে চালান',dockerBody:'Container non-root user হিসেবে চালান। SQLite-এ writable data directory mount করুন। command history-এর বদলে secret-injection mechanism দিয়ে tokens ও database passwords দিন।',databaseTitle:'Database',databaseBody1:'SQLite, PostgreSQL বা MySQL connection-এর জন্য `DB_URI` ব্যবহার করুন। MariaDB, MySQL protocol-এ যুক্ত হয়। CMS query results snapshot হিসেবে cache করে এবং storage refresh সাময়িক ব্যর্থ হলে শেষ সফল snapshot দিতে থাকে।',databaseBody2:'`DB_CACHE_SECS` snapshot refresh interval এবং `DB_QUERY_TIMEOUT_SECS` refresh query limit সেট করে। সফল snapshot না থাকলে ও storage পড়া না গেলে service `DAT_STORE_UNAVAILABLE` দেয়।',rolesTitle:'Access roles',roleHeaders:['Environment variable','Permission','ব্যবহারকারী'],roleRows:[['Certificates register ও protected version সংগ্রহ','Operations'],['Full certificates সংগ্রহ','DAT issuing services'],['Verify-only certificates সংগ্রহ','Verification ও decryption services']],rolesNote:'প্রতিটি variable comma-separated alphanumeric tokens নেয়। কোনো role-এর token list খালি হলে endpoints খোলা হয় এবং warning log হয়।',certificateTitle:'Certificate generation',certificateBody:'Master role signature algorithm, encryption algorithm, propagation delay, issuance period ও TTL দিয়ে certificate register করে। propagation delay-তে issuable হওয়ার আগে services নতুন certificate synchronize করে।',clientTitle:'Client integration',clientSteps:['Issuing services-এ full token ও full-certificate endpoint ব্যবহার করুন।','Verifying services-এ verify token ও verify-only option ব্যবহার করুন।','প্রথম synchronization result দেখুন; startup ব্যর্থ করতে immediate synchronization API call করুন।','Automatic synchronization চালু থাকলে shutdown-এ manager বন্ধ করুন।'],libraryBefore:'প্রতিটি ভাষার builder ও shutdown behavior-এর জন্য ',libraryLink:'library guides',libraryAfter:' দেখুন।',operationsTitle:'Operational checks',operationsItems:['`/health` ও `/version/api` authentication ছাড়াই status জানায়।','Role configured থাকলে `/version`-এ master token লাগে।','Standard output ও standard error থেকে logs সংগ্রহ করুন।','Shutdown signals forward করে database ও scheduler বন্ধের সময় দিন।'],kubernetesTitle:'Kubernetes',kubernetesBody:'Container port ও probes service port-এর সঙ্গে মিলিয়ে non-root user-এর write access-সহ data directory mount করুন। Secrets দিয়ে tokens ও database connection details inject করুন।'}
}
