import type { SharedGuideLocale } from './types'

export const urGuideLocale: SharedGuideLocale = {
 libraryIndex:{title:'Libraries',intro:'اپنی application کی زبان کا DAT client منتخب کریں۔ ہر client یکساں DAT اور certificate specifications استعمال کرتا اور local certificate management اور DAT CMS synchronization فراہم کرتا ہے۔',criteriaTitle:'انتخاب کیسے کریں',criteriaBody:'DAT issue کرنے والی service کو full certificates استعمال کرنے چاہییں۔ صرف verify اور decrypt کرنے والی service کو ECDSA verify-only certificates اور CMS verify-only role استعمال کرنا چاہیے۔',flowTitle:'Guide کی ساخت',flowBody:'ہر library guide میں installation، آسان issuance اور verification flow، DAT CMS connection، synchronization policy، shutdown اور error handling شامل ہیں۔'},
 library:{titleSuffix:'Library',install:'Installation',quickTitle:'فوری آغاز',quickIntro:'یہ مکمل flow CMS سے certificates لیتا، JSON data والا DAT بناتا اور verify کرتا ہے۔',stepTitle:'مرحلہ وار',connectTitle:'1. CMS سے connect کریں',connectBody:'Issuing service full certificates کا token استعمال کرتی ہے۔ startup پر فوراً synchronization سے certificates ملنے سے پہلے issuance نہیں ہوتا۔',issueTitle:'2. DAT issue کریں',issueBody:'یہ مثال public JSON کو `plain` اور protected user information کو JSON کی صورت `secure` میں رکھتی ہے۔',parseTitle:'3. DAT verify کریں',parseBody:'`parse` expiration اور signature check کرکے `secure` decrypt کرتا ہے۔ صرف successful verification کے بعد ملنے والا payload استعمال کریں۔',functionsTitle:'اہم functions',functionHeader:'Function',purposeHeader:'مقصد',dataTitle:'Data regions',plainBody:'signed مگر encrypted نہ ہونے والے bytes۔',secureBody:'encrypted bytes۔',payloadBody:'صرف `parse` کامیاب ہونے کے بعد اعتماد کریں۔',optionsTitle:'JSON کے علاوہ options',optionsBody:'مثالوں میں معروف JSON ہے۔ تیز processing کے لیے binary data، JSON serialization اور parsing سے بچ کر data size کم کر سکتا ہے۔',formatsBody:'Simple values text کی صورت یا structured data کو Protobuf یا MessagePack جیسے binary formats میں `plain` اور `secure` میں رکھیں۔',verifyTitle:'Verify-only services',verifyBody:'DAT issue نہ کرنے والی service verify-only option اور verify-only token استعمال کرتی اور صرف `parse` call کرتی ہے۔',lifecycleTitle:'Shutdown اور errors',errorsBefore:'Error messages کے بجائے ',errorsLink:'error codes اور retry classifications',errorsAfter:' استعمال کریں۔'},
 guides:{
  rust:{binaryNote:'`issue` فی الحال strings لیتا ہے، arbitrary bytes کو Base64Url یا Hex میں encode کرکے verification کے بعد decode کریں۔',lifecycle:'آخری `Arc<DatCmsManager>` drop ہونے پر automatic synchronization task ختم ہوتا ہے۔',apiPurposes:['Certificates فوراً synchronize کرتا ہے۔','موجودہ issuing certificate سے DAT بناتا ہے۔','DAT verify کرکے payload دیتا ہے۔','آخری synchronization error دیتا ہے۔']},
  java:{binaryNote:'`ByteArray` overload اضافی format کے بغیر bytes براہِ راست محفوظ اور حاصل کرتا ہے۔',lifecycle:'`DatCmsManager`، `AutoCloseable` ہے؛ `use` یا `close()` سے بند کریں۔',apiPurposes:['Certificates فوراً synchronize کرکے failure بتاتا ہے۔','DAT بنا کر DatResult دیتا ہے۔','DAT verify کرکے Payload دیتا ہے۔','آخری background synchronization error دیتا ہے۔']},
  javascript:{binaryNote:'`Uint8Array` یا `ArrayBuffer` دیں اور `plainBytes` اور `secureBytes` سے اصل bytes لیں۔',lifecycle:'shutdown پر timers اور جاری requests صاف کرنے کے لیے `stop()` call کریں۔',apiPurposes:['Certificates فوراً synchronize کرتا ہے۔','Asynchronously DAT string بناتا ہے۔','DAT verify کرکے DatPayload دیتا ہے۔','آخری synchronization error دیتا ہے۔']},
  python:{binaryNote:'`bytes` براہِ راست دیں اور `plain_bytes` اور `secure_bytes` سے لیں۔',lifecycle:'automatic synchronization فعال ہو تو shutdown پر `stop()` call کریں۔',apiPurposes:['Certificates فوراً synchronize کرتا ہے۔','DAT string بناتا ہے۔','DAT verify کرکے DatPayload دیتا ہے۔','آخری synchronization error دیتا ہے۔']},
  csharp:{binaryNote:'`byte[]` overload اور `PlainBytes` و `SecureBytes` استعمال کریں۔',lifecycle:'manager اور background synchronization صاف کرنے کے لیے `await using` استعمال کریں۔',apiPurposes:['Certificates فوراً synchronize کرتا ہے۔','DAT string بناتا ہے۔','DAT verify کرکے Payload دیتا ہے۔','آخری synchronization error دیتا ہے۔']},
  go:{binaryNote:'Go strings bytes رکھ سکتی ہیں۔ byte slice کو `string` کے طور پر دے کر result واپس `[]byte` میں بدلیں۔',lifecycle:'automatic synchronization فعال ہو تو cleanup کے لیے `defer cms.Close()` استعمال کریں۔',apiPurposes:['Certificates فوراً synchronize کرتا ہے۔','DAT string اور error دیتا ہے۔','Verified Payload اور error دیتا ہے۔','آخری synchronization error دیتا ہے۔']},
  ruby:{binaryNote:'Binary strings دیں اور `plain_bytes` و `secure_bytes` سے حاصل کریں۔',lifecycle:'automatic synchronization فعال ہو تو background thread ختم کرنے کے لیے `stop` call کریں۔',apiPurposes:['Certificates فوراً synchronize کرتا ہے۔','DAT string بناتا ہے۔','DAT verify کرکے DatPayload دیتا ہے۔','آخری synchronization error دیتا ہے۔']},
  c:{binaryNote:'موجودہ C issuance API، NUL-terminated strings لیتا ہے۔ arbitrary bytes کو Base64Url یا Hex میں encode کرکے payload lengths سے result پڑھیں۔',lifecycle:'متعلقہ cleanup functions سے `dat`، `payload` اور `cms` release کریں۔',apiPurposes:['Certificates فوراً synchronize کرتا ہے۔','DAT string allocate کرکے دیتا ہے۔','Verified payload allocate کرکے دیتا ہے۔','آخری synchronization error دیتا ہے۔'],parse:`dat_payload_t *payload = NULL;
err = dat_cms_manager_parse(cms, dat, &payload);
/* plain_bytes اور secure_bytes کو ان کی متعلقہ lengths کے ساتھ استعمال کریں۔ */`,binary:`/* issue C strings لیتا ہے، اس لیے NUL والا data پہلے encode کریں۔ */
const char *secure_hex = "00ff1080";
char *dat = NULL;
err = dat_cms_manager_issue(cms, "01", secure_hex, &dat);

dat_payload_t *payload = NULL;
err = dat_cms_manager_parse(cms, dat, &payload);`}},
 cms:{introBefore:'DAT CMS certificates بناتا، database میں محفوظ کرتا اور issuing و verifying services کو مناسب certificates دیتا ہے۔ Protocol behavior کی تفصیل ',specLink:'DAT CMS specification',introAfter:' میں ہے۔',configTitle:'Runtime configuration بنائیں',dockerTitle:'Docker کے ساتھ چلائیں',dockerBody:'Container کو non-root user کے طور پر چلائیں۔ SQLite میں writable data directory mount کریں۔ tokens اور database passwords کو command history کے بجائے secret-injection mechanism سے دیں۔',databaseTitle:'Database',databaseBody1:'SQLite، PostgreSQL یا MySQL connection کے لیے `DB_URI` استعمال کریں۔ MariaDB، MySQL protocol سے connect ہوتا ہے۔ CMS query results کو snapshot میں cache کرتا اور storage refresh عارضی ناکام ہو تو آخری کامیاب snapshot دیتا رہتا ہے۔',databaseBody2:'`DB_CACHE_SECS` snapshot refresh interval اور `DB_QUERY_TIMEOUT_SECS` refresh queries کی limit مقرر کرتا ہے۔ کامیاب snapshot نہ ہو اور storage نہ پڑھا جا سکے تو service `DAT_STORE_UNAVAILABLE` دیتی ہے۔',rolesTitle:'Access roles',roleHeaders:['Environment variable','Permission','استعمال'],roleRows:[['Certificates register اور protected version حاصل کرنا','Operations'],['Full certificates حاصل کرنا','DAT issuing services'],['Verify-only certificates حاصل کرنا','Verification اور decryption services']],rolesNote:'ہر variable comma-separated alphanumeric tokens لیتا ہے۔ role کی token list خالی ہو تو endpoints کھل جاتے اور warning log ہوتی ہے۔',certificateTitle:'Certificate generation',certificateBody:'Master role signature algorithm، encryption algorithm، propagation delay، issuance period اور TTL بتا کر certificate register کرتا ہے۔ propagation delay میں services certificate کے issuable ہونے سے پہلے اسے synchronize کرتی ہیں۔',clientTitle:'Client integration',clientSteps:['Issuing services کے لیے full token اور full-certificate endpoint استعمال کریں۔','Verifying services کے لیے verify token اور verify-only option استعمال کریں۔','پہلے synchronization کا result check کریں؛ startup ناکام کرنا ہو تو immediate synchronization API call کریں۔','Automatic synchronization فعال ہو تو shutdown پر manager بند کریں۔'],libraryBefore:'ہر زبان کے builder اور shutdown behavior کے لیے ',libraryLink:'library guides',libraryAfter:' دیکھیں۔',operationsTitle:'Operational checks',operationsItems:['`/health` اور `/version/api` بغیر authentication status بتاتے ہیں۔','Role configured ہو تو `/version` کے لیے master token درکار ہے۔','Standard output اور standard error سے logs جمع کریں۔','Shutdown signals forward کرکے database اور scheduler کو بند ہونے کا وقت دیں۔'],kubernetesTitle:'Kubernetes',kubernetesBody:'Container port اور probes کو service port سے ملائیں، اور non-root user کے write access کے ساتھ data directory mount کریں۔ Secrets سے tokens اور database connection details inject کریں۔'}
}
