import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..', '..')
const outFile = join(repoRoot, 'dat-web', 'docs', '.vitepress', 'src', 'bench.ts')

const TARGETS = [
  { target: 'Rust', link: '/libs/cargo-dat', readme: 'dat-rust/README.md' },
  { target: 'Go', link: '/libs/go-saro-dat', readme: 'dat-go/v4/README.md' },
  { target: 'Java / Kotlin', link: '/libs/maven-me.saro-dat', readme: 'dat-maven/README.md' },
  { target: 'JavaScript', link: '/libs/npm-saro-dat', readme: 'dat-npm/README.md' },
  { target: 'C#', link: '/libs/nuget-saro-dat', readme: 'dat-nuget/README.md' },
  { target: 'Python', link: '/libs/pypi-saro-dat', readme: 'dat-pypi/README.md' },
  { target: 'Ruby', link: '/libs/gems-saro-dat', readme: 'dat-ruby/README.md' },
  { target: 'C / C++', link: '/libs/vcpkg-dat', readme: 'dat-vcpkg/README.md' },
]

const SIGS = ['HMAC-SHA256-MFS', 'HMAC-SHA384-MFS', 'HMAC-SHA512-MFS', 'ECDSA-P256', 'ECDSA-P384', 'ECDSA-P521']
const CRYPTOS = ['IV-AES128-GCM', 'IV-AES256-GCM']
const RUNS = 10000

function normalizeAlg(name) {
  if (name.includes('-')) {
    return name.toUpperCase()
  }
  return name.replace(/(?<=[a-z0-9])(?=[A-Z])/g, '-').toUpperCase()
}

function parseReadme(path) {
  const text = readFileSync(join(repoRoot, path), 'utf8')
  const perfAt = text.search(/^#+ +Performance\s*$/m)
  if (perfAt < 0) {
    throw new Error(`${path}: no Performance section`)
  }
  const section = text.slice(perfAt)
  const sets = { multi: new Map(), single: new Map() }
  let mode = null
  for (const raw of section.split('\n')) {
    const line = raw.trim()
    if (/^-*\s*Multi-Thread\s*-*$/.test(line)) {
      mode = 'multi'
      continue
    }
    if (/^-*\s*Single-Thread\s*-*$/.test(line)) {
      mode = 'single'
      continue
    }
    const m = line.match(/^(\S+) (\S+) (Issue|Parse) \* (\d+) : (\d+)ms$/)
    if (!m || !mode) {
      continue
    }
    if (Number(m[4]) !== RUNS) {
      throw new Error(`${path}: unexpected run count ${m[4]} in "${line}"`)
    }
    const sig = normalizeAlg(m[1])
    const crypto = normalizeAlg(m[2])
    const key = `${sig} ${crypto}`
    const entry = sets[mode].get(key) ?? { sig, crypto }
    entry[m[3] === 'Issue' ? 'issueMs' : 'parseMs'] = Number(m[5])
    sets[mode].set(key, entry)
  }
  for (const [modeName, map] of Object.entries(sets)) {
    for (const sig of SIGS) {
      for (const crypto of CRYPTOS) {
        const entry = map.get(`${sig} ${crypto}`)
        if (!entry || entry.issueMs === undefined || entry.parseMs === undefined) {
          throw new Error(`${path}: ${modeName} is missing ${sig} ${crypto}`)
        }
      }
    }
    if (map.size !== SIGS.length * CRYPTOS.length) {
      throw new Error(`${path}: ${modeName} has unexpected extra cases`)
    }
  }
  const ordered = (map) =>
    SIGS.flatMap((sig) => CRYPTOS.map((crypto) => map.get(`${sig} ${crypto}`)))
  return { multi: ordered(sets.multi), single: ordered(sets.single) }
}

function renderCases(cases) {
  return cases
    .map((c) => `      { sig: '${c.sig}', crypto: '${c.crypto}', issueMs: ${c.issueMs}, parseMs: ${c.parseMs} },`)
    .join('\n')
}

const series = TARGETS.map((t) => ({ ...t, ...parseReadme(t.readme) }))

const body = series
  .map(
    (s) => `  {
    target: '${s.target}',
    link: '${s.link}',
    source: '${s.readme}',
    multi: [
${renderCases(s.multi)}
    ],
    single: [
${renderCases(s.single)}
    ],
  },`,
  )
  .join('\n')

const out = `// generated by dat-web/tools/bench-gen.mjs from each library README's Performance section.
// do not edit by hand — update the README and run \`npm run bench:gen\` in dat-web.
export const BENCH_RUNS = ${RUNS}

export const BENCH_MACHINE = 'mac mini m4 2024 basic (10 core)'

export const BENCH_SIGS = [${SIGS.map((s) => `'${s}'`).join(', ')}] as const

export const BENCH_CRYPTOS = [${CRYPTOS.map((s) => `'${s}'`).join(', ')}] as const

export type BenchCase = {
  sig: string
  crypto: string
  issueMs: number
  parseMs: number
}

export type BenchSeries = {
  target: string
  link: string
  source: string
  multi: BenchCase[]
  single: BenchCase[]
}

export const BENCH_SERIES: BenchSeries[] = [
${body}
]
`

writeFileSync(outFile, out)
console.log(`wrote ${outFile}: ${series.length} series, ${series.length * 2 * SIGS.length * CRYPTOS.length} cases`)
