from __future__ import annotations

from enum import Enum
from typing import Optional

TOKEN_MALFORMED = "DAT_TOKEN_MALFORMED"
TOKEN_EXPIRED = "DAT_TOKEN_EXPIRED"
TOKEN_UNKNOWN = "DAT_TOKEN_UNKNOWN"

CERT_MALFORMED = "DAT_CERT_MALFORMED"
CERT_EXPIRED = "DAT_CERT_EXPIRED"
CERT_NOT_YET_ISSUABLE = "DAT_CERT_NOT_YET_ISSUABLE"
CERT_ISSUANCE_ENDED = "DAT_CERT_ISSUANCE_ENDED"
CERT_VERIFY_ONLY = "DAT_CERT_VERIFY_ONLY"
CERT_NOT_FOUND = "DAT_CERT_NOT_FOUND"
CERT_NOT_SYNCED = "DAT_CERT_NOT_SYNCED"
CERT_DUPLICATE_CID = "DAT_CERT_DUPLICATE_CID"
CERT_UNKNOWN = "DAT_CERT_UNKNOWN"

SIG_MISMATCH = "DAT_SIG_MISMATCH"
SIG_MALFORMED = "DAT_SIG_MALFORMED"
SIG_KEY_MISSING = "DAT_SIG_KEY_MISSING"
SIG_BACKEND = "DAT_SIG_BACKEND"
SIG_UNKNOWN = "DAT_SIG_UNKNOWN"

CRYPTO_TAG_MISMATCH = "DAT_CRYPTO_TAG_MISMATCH"
CRYPTO_DATA_INVALID = "DAT_CRYPTO_DATA_INVALID"
CRYPTO_BACKEND = "DAT_CRYPTO_BACKEND"
CRYPTO_UNKNOWN = "DAT_CRYPTO_UNKNOWN"

KEY_INVALID = "DAT_KEY_INVALID"
KEY_VERIFY_ONLY_UNSUPPORTED = "DAT_KEY_VERIFY_ONLY_UNSUPPORTED"
KEY_UNKNOWN = "DAT_KEY_UNKNOWN"

MANAGER_NO_CERTIFICATE = "DAT_MANAGER_NO_CERTIFICATE"
MANAGER_NO_ISSUABLE_CERTIFICATE = "DAT_MANAGER_NO_ISSUABLE_CERTIFICATE"
MANAGER_DISPOSED = "DAT_MANAGER_DISPOSED"
MANAGER_UNKNOWN = "DAT_MANAGER_UNKNOWN"

CMS_UNREACHABLE = "DAT_CMS_UNREACHABLE"
CMS_UNAUTHORIZED = "DAT_CMS_UNAUTHORIZED"
CMS_FORBIDDEN = "DAT_CMS_FORBIDDEN"
CMS_ENDPOINT_NOT_FOUND = "DAT_CMS_ENDPOINT_NOT_FOUND"
CMS_SERVER_ERROR = "DAT_CMS_SERVER_ERROR"
CMS_HTTP_STATUS = "DAT_CMS_HTTP_STATUS"
CMS_MALFORMED = "DAT_CMS_MALFORMED"
CMS_IMPORT_FAILED = "DAT_CMS_IMPORT_FAILED"
CMS_VERSION_RESET = "DAT_CMS_VERSION_RESET"
CMS_NOT_SYNCED = "DAT_CMS_NOT_SYNCED"
CMS_SYNC_IN_PROGRESS = "DAT_CMS_SYNC_IN_PROGRESS"
CMS_NOT_SUPPORTED = "DAT_CMS_NOT_SUPPORTED"
CMS_UNKNOWN = "DAT_CMS_UNKNOWN"

CONFIG_ALG_UNSUPPORTED = "DAT_CONFIG_ALG_UNSUPPORTED"
CONFIG_URI_INVALID = "DAT_CONFIG_URI_INVALID"
CONFIG_ARGUMENT_INVALID = "DAT_CONFIG_ARGUMENT_INVALID"
CONFIG_UNKNOWN = "DAT_CONFIG_UNKNOWN"

INTERNAL_UNAVAILABLE = "DAT_INTERNAL_UNAVAILABLE"
INTERNAL_UNKNOWN = "DAT_INTERNAL_UNKNOWN"


class DatRetry(str, Enum):
    TRANSIENT = "transient"
    PERMANENT = "permanent"
    STATE = "state"


_TRANSIENT = frozenset({
    CERT_NOT_YET_ISSUABLE, CERT_NOT_SYNCED, MANAGER_NO_CERTIFICATE,
    CMS_UNREACHABLE, CMS_SERVER_ERROR, CMS_NOT_SYNCED,
})

_STATE = frozenset({CMS_VERSION_RESET, CMS_SYNC_IN_PROGRESS})

_SECURITY = frozenset({SIG_MISMATCH, CRYPTO_TAG_MISMATCH})


class DatError(ValueError, RuntimeError):
    def __init__(self, code: str, detail: Optional[str] = None, cause: Optional[BaseException] = None):
        super().__init__(f"{code}: {detail}" if detail else code)
        self.code = code
        self.detail = detail
        if cause is not None:
            self.__cause__ = cause

    @property
    def retry(self) -> DatRetry:
        if self.code == MANAGER_NO_ISSUABLE_CERTIFICATE:
            cause = self.__cause__
            if isinstance(cause, DatError) and cause.code == CERT_NOT_YET_ISSUABLE:
                return DatRetry.TRANSIENT
            return DatRetry.PERMANENT
        if self.code in _TRANSIENT:
            return DatRetry.TRANSIENT
        if self.code in _STATE:
            return DatRetry.STATE
        return DatRetry.PERMANENT

    @property
    def security_event(self) -> bool:
        return self.code in _SECURITY

    def __repr__(self) -> str:
        return f"DatError({self.code!r}, {self.detail!r})"


def code_of(e: BaseException) -> Optional[str]:
    return e.code if isinstance(e, DatError) else None
